version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando pre-build"
      - echo "Instalando dependencias o configuraciones previas al build" 
      - aws --version
      - aws --region eu-west-1 ecr get-login-password || echo "Fallo al obtener el token de login de ECR"
      - aws --region eu-west-1 ecr get-login-password | docker login --username AWS --password-stdin $AWS_ID.dkr.ecr.eu-west-1.amazonaws.com
 
      - aws --region eu-south-2 ecr get-login-password | docker login --username AWS --password-stdin $AWS_ID.dkr.ecr.eu-south-2.amazonaws.com
  build:
    commands:
      - echo "Iniciando build"
      - echo "Definiendo URIs de los repositorios de pull y push" 
      - REPOSITORY_URI=$AWS_ID.dkr.ecr.eu-west-1.amazonaws.com/aws_repository_app
      - REPOSITORY_DEST=$AWS_ID.dkr.ecr.eu-south-2.amazonaws.com/first_app_spain
      - echo "Haciendo pull de extraccion"
      - docker pull $REPOSITORY_URI:latest
      - echo "Haciendo tag del repositorio"
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_DEST:latest
      - echo "Haciendo el push en el destino"
      - docker push $REPOSITORY_DEST:latest
  post_build:
    commands:
      - echo "Finalizando post-build"
      - echo "Realizando acciones posteriores al build"
      

artifacts:
  files:
    - '**/*'  # Incluye todos los archivos como artefactos del build
